### ISSUE TITLE
"create opinion" button could turn into "update opinion" button

### ISSUE THREAD

**Issue by Iwan-Ittermann** [digital-peace-talks/DPT#59] opened 2020-01-09 12:46 UTC
**Is your feature request related to a problem? Please describe.**
While the "new opinion" button is located inside the GUI, the very similar button "edit opinion" is located inside the 3D environment.   
Once one opinion got published the "new" button creates an error that we should catch before it happens.  

**Describe the solution you'd like**
The "new opinion" button could turn into an "edit opinion" button once the user published the first opinion. 
If the user clicks on the button, he will be presented with the "create opinion" form but his original text will be preset. 
If the user changes the text of the opinion, the old version will be saved and displayed in the context frame. 

**Describe alternatives you've considered**
There could be an "my opinions" control center where people can easily locate and update all their opinions. Yet this would rather work in addition as users must have the possibility to edit their opinion when looking at it inside the topic.

**Comment by avirankatzsofi** [comment] 2020-03-25 09:02
Duplicate of #69

**Closed by avirankatzsofi** 2020-03-25 09:02 UTC
Labels: Toolbar, enhancement

**Comment by Iwan-Ittermann** [comment] 2020-03-25 09:15
One difference: 

> If the user changes the text of the opinion, the old version will be saved and displayed in the context frame.
